### ISSUE TITLE
Support for single-quoted strings with double-quoted strings within them

### ISSUE THREAD

**Issue by dylan-sa** [OxfordSemantic/vscode-rdfox-rdf#4]
Kind of an edge case here, but something I encountered recently. Currently, it appears that the extension is not capturing single-quoted strings that have double-quoted strings within them. For example, it wouldn't catch the following:

`ex:Class skos:scopeNote 'This is an example scope note with a "double-quoted string" on the inside.'^^xsd:string .` 

(Conversely, it does catch double-quoted strings with single-quoted strings on the inside.)

Again, probably not something people will run into too often, but just thought I'd bring it to your attention. Thanks.

**Comment by DianaMarksOST** [comment]
Thank you for letting us know, the issue should now be fixed in version 1.0.4
