### ISSUE TITLE
'mod' shows up with SPARQL function highlighting within a variable

### ISSUE THREAD

**Issue by dylan-sa** [OxfordSemantic/vscode-rdfox-rdf#6]
In SPARQL queries, if I use a variable containing the string 'mod' (e.g., `?business_model`), the 'mod' portion of the variable shows up as yellow (like it generally does for SPARQL functions). Very minor issue, but would be great to have 'mod' show up as yellow when used as a function and have no highlighting when it's used in a variable.

**Comment by DianaMarksOST** [comment]
Hi Dylan,
thanks for letting us know about this, the issue has been fixed in commit 934930e9d58b97f531eaad16a708eb8ebdb30dfa, which will be included in the next release of the extension.

**Comment by dylan-sa** [comment]
Great!
